INSERT INTO EMPLOYEE VALUES(1,'RAMANA','INDIA');
INSERT INTO EMPLOYEE VALUES(2,'BHARADWAJ','INDIA');
INSERT INTO EMPLOYEE VALUES(3,'RISHI','INDIA');
INSERT INTO EMPLOYEE VALUES(4,'VAMSHI','INDIA');
INSERT INTO EMPLOYEE VALUES(5,'NAGENDRA','INDIA');
